dist: xenial
os:
  - linux
language:
  - cpp
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run the build commands next
  - >
      cmake -DBUILD_TESTS=ON -DCODE_COVERAGE=ON . && make
      && cd sample && cmake -DCODE_COVERAGE=ON . && make && cd -
      && ./tests/endstream_tests && ./sample/endstream_sample
after_success:
  - coveralls --include src --gcov-options '\-lp'

notifications:
  email:
    recipients:
      - thermostatico@gmail.com
    on_success: change
    on_failure: always
